function roll(num){
	if(num <= 15) return { "name": "+1 Weapon", "link":"https://www.dndbeyond.com/magic-items/weapon-1" };
	if(num <= 18) return { "name": "+1 Shield", "link":"https://www.dndbeyond.com/magic-items/shield-1" };
	if(num <= 21) return { "name": "Sentinel Shield", "link":"https://aversten.obsidianportal.com/wiki_pages/sentinel-shield" };
	if(num <= 23) return { "name": "Amulet of Proof against Detection and Location", "link":"https://www.dndbeyond.com/magic-items/amulet-of-proof-against-detection-and-location" };
	if(num <= 25) return { "name": "Boots of Elvenkind", "link":"https://www.dndbeyond.com/magic-items/boots-of-elvenkind" };
	if(num <= 27) return { "name": "Boots of Striding and Springing", "link":"https://www.dndbeyond.com/magic-items/boots-of-striding-and-springing" };
	if(num <= 29) return { "name": "Bracers of Archery", "link":"https://www.dndbeyond.com/magic-items/bracers-of-archery" };
	if(num <= 31) return { "name": "Brooch of Shielding", "link":"https://www.dndbeyond.com/magic-items/brooch-of-shielding" };
	if(num <= 33) return { "name": "Broom of Flying", "link":"https://www.dndbeyond.com/magic-items/broom-of-flying" };
	if(num <= 35) return { "name": "Cloak of Elvenkind", "link":"https://www.dndbeyond.com/magic-items/cloak-of-elvenkind" };
	if(num <= 37) return { "name": "Cloak of Protection", "link":"https://www.dndbeyond.com/magic-items/cloak-of-protection" };
	if(num <= 39) return { "name": "Gauntlets of Ogre Power", "link":"https://www.dndbeyond.com/magic-items/gauntlets-of-ogre-power" };
	if(num <= 41) return { "name": "Hat of Disguise", "link":"https://www.dndbeyond.com/magic-items/hat-of-disguise" };
	if(num <= 43) return { "name": "Javelin of Lightning", "link":"https://www.dndbeyond.com/magic-items/javelin-of-lightning" };
	if(num <= 45) return { "name": "Pearl of Power", "link":"https://www.dndbeyond.com/magic-items/pearl-of-power" };
	if(num <= 47) return { "name": "+1 Rod of the Pact Keeper", "link":"https://www.dndbeyond.com/magic-items/rod-of-the-pact-keeper-1" };
	if(num <= 49) return { "name": "Slippers of Spider Climbing", "link":"https://www.dndbeyond.com/magic-items/slippers-of-spider-climbing" };
	if(num <= 51) return { "name": "Staff of the Adder", "link":"https://www.dndbeyond.com/magic-items/staff-of-the-adder" };
	if(num <= 53) return { "name": "Staff of the Python", "link":"https://www.dndbeyond.com/magic-items/staff-of-the-python" };
	if(num <= 55) return { "name": "Sword of Vengeance", "link":"https://www.dndbeyond.com/magic-items/sword-of-vengeance" };
	if(num <= 57) return { "name": "Trident of Fish Command", "link":"https://www.dndbeyond.com/magic-items/trident-of-fish-command" };
	if(num <= 59) return { "name": "Wand of Magic Missiles", "link":"https://www.dndbeyond.com/magic-items/wand-of-magic-missiles" };
	if(num <= 61) return { "name": "+1 Wand of the War Mage", "link":"https://www.dndbeyond.com/magic-items/wand-of-the-war-mage-1" };
	if(num <= 63) return { "name": "Wand of Web", "link":"https://www.dndbeyond.com/magic-items/wand-of-web" };
	if(num <= 65) return { "name": "Weapon of Warning", "link":"https://www.dndbeyond.com/magic-items/weapon-of-warning" };
	if(num <= 66) return { "name": "Adamantine Armor (chain mail)", "link":"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(num <= 67) return { "name": "Adamantine Armor (chain shirt)", "link":"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(num <= 68) return { "name": "Adamantine Armor (scale mail)", "link":"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(num <= 69) return { "name": "Bag of Tricks (gray)", "link":"https://www.dndbeyond.com/magic-items/bag-of-tricks" };
	if(num <= 70) return { "name": "Bag of Tricks (rust)", "link":"https://www.dndbeyond.com/magic-items/bag-of-tricks" };
	if(num <= 71) return { "name": "Bag of Tricks (tan)", "link":"https://www.dndbeyond.com/magic-items/bag-of-tricks" };
	if(num <= 72) return { "name": "Boots of the Winterlands", "link":"https://www.dndbeyond.com/magic-items/boots-of-the-winterlands" };
	if(num <= 73) return { "name": "Circlet of Blasting", "link":"https://www.dndbeyond.com/magic-items/circlet-of-blasting" };
	if(num <= 74) return { "name": "Deck of Illusions", "link":"https://www.dndbeyond.com/magic-items/deck-of-illusions" };
	if(num <= 75) return { "name": "Eversmoking Bottle", "link":"https://www.dndbeyond.com/magic-items/eversmoking-bottle" };
	if(num <= 76) return { "name": "Eyes of Charming", "link":"https://www.dndbeyond.com/magic-items/eyes-of-charming" };
	if(num <= 77) return { "name": "Eyes of the Eagle", "link":"https://www.dndbeyond.com/magic-items/eyes-of-the-eagle" };
	if(num <= 78) return { "name": "Figurine of Wondrous Power (silver raven)", "link":"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power" };
	if(num <= 79) return { "name": "Gem of Brightness", "link":"https://www.dndbeyond.com/magic-items/gem-of-brightness" };
	if(num <= 80) return { "name": "Gloves of Missile Snaring", "link":"https://www.dndbeyond.com/magic-items/gloves-of-missile-snaring" };
	if(num <= 81) return { "name": "Gloves of Swimming and Climbing", "link":"https://www.dndbeyond.com/magic-items/gloves-of-swimming-and-climbing" };
	if(num <= 82) return { "name": "Gloves of Thievery", "link":"https://www.dndbeyond.com/magic-items/gloves-of-thievery" };
	if(num <= 83) return { "name": "Headband of Intellect", "link":"https://www.dndbeyond.com/magic-items/headband-of-intellect" };
	if(num <= 84) return { "name": "Helm of Telepathy", "link":"https://www.dndbeyond.com/magic-items/helm-of-telepathy" };
	if(num <= 85) return { "name": "Instrument of the Bards (Doss lute)", "link":"https://www.dndbeyond.com/magic-items/instrument-of-the-bards" };
	if(num <= 86) return { "name": "Instrument of the Bards (Fochlucan bandore)", "link":"https://www.dndbeyond.com/magic-items/instrument-of-the-bards" };
	if(num <= 87) return { "name": "Instrument of the Bards (Mac-Fuirmidh cittern)", "link":"https://www.dndbeyond.com/magic-items/instrument-of-the-bards" };
	if(num <= 88) return { "name": "Medallion of Thoughts", "link":"https://www.dndbeyond.com/magic-items/medallion-of-thoughts" };
	if(num <= 89) return { "name": "Necklace of Adaptation", "link":"https://www.dndbeyond.com/magic-items/necklace-of-adaptation" };
	if(num <= 90) return { "name": "Periapt of Wound Closure", "link":"https://www.dndbeyond.com/magic-items/periapt-of-wound-closure" };
	if(num <= 91) return { "name": "Pipes of Haunting", "link":"https://www.dndbeyond.com/magic-items/pipes-of-haunting" };
	if(num <= 92) return { "name": "Pipes of the Sewers", "link":"https://www.dndbeyond.com/magic-items/pipes-of-the-sewers" };
	if(num <= 93) return { "name": "Ring of Jumping", "link":"https://www.dndbeyond.com/magic-items/ring-of-jumping" };
	if(num <= 94) return { "name": "Ring of Mind Shielding", "link":"https://www.dndbeyond.com/magic-items/ring-of-mind-shielding" };
	if(num <= 95) return { "name": "Ring of Warmth", "link":"https://www.dndbeyond.com/magic-items/ring-of-warmth" };
	if(num <= 96) return { "name": "Ring of Water Walking", "link":"https://www.dndbeyond.com/magic-items/ring-of-water-walking" };
	if(num <= 97) return { "name": "Quiver of Ehlonna", "link":"https://www.dndbeyond.com/magic-items/quiver-of-ehlonna" };
	if(num <= 98) return { "name": "Stone of Good Luck", "link":"https://www.dndbeyond.com/magic-items/stone-of-good-luck" };
	if(num <= 99) return { "name": "Wind Fan", "link":"https://www.dndbeyond.com/magic-items/wind-fan" };
	return { "name": "Winged Boots", "link":"https://www.dndbeyond.com/magic-items/winged-boots" };
}


export default roll;